const express = require('express');
const router = express.Router();
const { getCustomers, getCustomer, updateCustomer, deleteCustomer, getCustomerStats } = require('../controllers/customerController');
const { protect, authorize } = require('../middleware/auth');
router.get('/', protect, authorize('admin', 'staff'), getCustomers);
router.get('/stats', protect, authorize('admin', 'staff'), getCustomerStats);
router.get('/:id', protect, authorize('admin', 'staff'), getCustomer);
router.put('/:id', protect, authorize('admin'), updateCustomer);
router.delete('/:id', protect, authorize('admin'), deleteCustomer);
module.exports = router;
