const express = require('express');
const router = express.Router();
const { getMenuItems, getMenuItem, createMenuItem, updateMenuItem, deleteMenuItem, getStats } = require('../controllers/menuController');
const { protect, authorize } = require('../middleware/auth');
router.get('/', getMenuItems);
router.get('/stats', protect, authorize('admin', 'staff'), getStats);
router.get('/:id', getMenuItem);
router.post('/', protect, authorize('admin'), createMenuItem);
router.put('/:id', protect, authorize('admin'), updateMenuItem);
router.delete('/:id', protect, authorize('admin'), deleteMenuItem);
module.exports = router;
