const express = require('express');
const router = express.Router();
const { getOrders, getOrder, createOrder, updateOrderStatus, deleteOrder } = require('../controllers/orderController');
const { protect, authorize } = require('../middleware/auth');
router.get('/', protect, getOrders);
router.get('/:id', protect, getOrder);
router.post('/', protect, createOrder);
router.put('/:id/status', protect, authorize('admin', 'staff'), updateOrderStatus);
router.delete('/:id', protect, authorize('admin'), deleteOrder);
module.exports = router;
